repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (^\.secrets\.baseline$)|
          (^\.config/coc/)|
          (^\.config/raycast/)|
          (^\.config/flutter/)|
          (^\.config/xbuild/)|
          (^\.config/GameMakerStudio2/)|
          (node_modules)|
          (package-lock\.json)
