# after-login-command = []
# after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# TODO: learn what is this?
# non-empty-workspaces-root-containers-layout-on-startup = 'smart'

accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.bottom = 0
outer.left = 0
outer.right = 0
outer.top = 0

[mode.main.binding]
# TODO: come up with a more intuitive keybinding for this?
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# TODO: integrate with tmux vim navigation
alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

# TODO: is this helpful? How does it work?
# alt-shift-n = 'split opposite'
alt-shift-minus = 'resize smart -100'
alt-shift-equal = 'resize smart +100'

alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode layout'

# TODO: come up with a mode that works for me (resizing, moving?)
[mode.layout.binding]
esc = ['mode main']
e = 'layout accordion horizontal vertical'
h = 'move left'
j = 'move down'
k = 'move up'
l = 'move right'
alt-h = 'join-with left'
alt-j = 'join-with down'
alt-k = 'join-with up'
alt-l = 'join-with right'
f = 'fullscreen'
0 = ['flatten-workspace-tree', 'mode main']
g = ['layout floating tiling', 'mode main']
minus = 'resize smart -100'
equal = 'resize smart +100'
