name: Update Nix Packages

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-nix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check and Update flake.lock
        if: ${{ hashFiles('flake.nix') != '' }}
        run: |
          nix flake update
          echo "::group::flake.lock diff"
          git diff flake.lock || true
          echo "::endgroup::"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request if flake.lock changed
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update Nix flake.lock"
          title: "chore: update Nix flake.lock"
          body: |
            This PR was automatically created by GitHub Actions to keep Nix flake inputs up to date.
          branch: update-nix-flake
          delete-branch: true
