name: Update NVChad Config

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update-nvchad:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull latest NVChad config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          if [ -d "nvim" ]; then
            git subtree pull --prefix=nvim https://github.com/mgastonportillo/nvchad-config.git main --squash
          else
            git subtree add --prefix=nvim https://github.com/mgastonportillo/nvchad-config.git main --squash
          fi
          git push
